name: Deploy Functions
on:
  push:
    branches:
      - firebase_setup
    paths:
      - '.github/workflows/firebase_functions.yaml'
      - 'functions/**'
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '22.x'
            - name: Install Dependencies
              run: cd functions && npm install
            - name: Run eslint
              run: cd functions && npm run lint
            - name: Build
              run: cd functions && npm run build
            - name: Save Service Account Key
              run: echo $GCP_SA_KEY > service-account.json
              env: 
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
            - name: "Print service-account email"
              run: cat service-account.json | jq -r '.client_email'
            - name: Deploy
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
