name: Deploy Storage Rules
on:
  push:
    branches:
      - firebase_setup
    paths:
      - 'storage.rules'
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - name: Deploy
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only storage
              env:
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
