name: Deploy Functions
on:
  push:
    branches:
      - firebase_setup
    paths:
      - 'functions/**'
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - run: npm install -g firebase-tools
            - run: cd functions && npm install
            - run: cd functions && npm run build
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions
              env:
                GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
